fastai/fastai_dev

docs/_layouts/default.html
This fix highlights menu item based on the URL.
=> Update sidebar to highlight current page

docs/gen_doc.html, docs_src/gen_doc.ipynb
Fix a typo in gen_docs and also learn how to make a PR to docs.
=> fix typo and learn to PR on fastai-docs

docs_src/callbacks.ipynb
=> Added GradientClipping to callbacks list

docs_src/vision.learner.ipynb
Docs adjustments for https://github.com/fastai/fastai/pull/1022
=> Confusion matric iterative computation docs added

dev_swift/04_callbacks.ipynb
Start porting `04_callbacks.ipynb` to Swift.
The top code cell is a prototype of `class Runner`, ported to Swift as
`struct Trainer`.
No other content has been ported yet.
=> [Swift] Start prototype `Trainer` abstraction.

dev_course/dl2/pascal.ipynb
respnsible -> responsible   
diferent -> different   
boxe ……-> boxes
=> fix typos   

dev_course/dl2/02b_initializing.ipynb
Thank you so much for a very clear and precise explanation!
I noticed this while re-watching the video. `i` starts from 0 so I believe `a @ x` happened 29 times - but it's quite possible `i` wasn't 28 on a different machine...?
=> Fixing a minor typo

dev_swift/05_callbacks2.ipynb
This notebook builds off of @dan-zheng's notebook to definte a training loop.
The callbacks here are just a start, but attempt to give a flavor of how a
callback system might fit into S4TF.
=> Add a prototype with a couple callbacks and a trainig loop w/callbacks.

dev_swift/02b_initializing.ipynb
Note: There is a part I got stuck on (torch norm()). PTAL at that.
=> Weight initialization notebook.

dev_swift/05b_early_stopping.ipynb
Note: There is a lot of overlap with @sgugger 's notebook: 05_annealing in the second part. I wasn't sure what to do about it, so I just finished this one. Also note that this is heavily based on @sgugger 's notebook.
=> Update early stopping to be a translation of the python one.

dev_swift/07_batchnorm.ipynb
Will add XLA compilation tomorrow.
=> Add Swift notebook for BatchNorm and Running BatchNorm

dev_swift/00_load_data.ipynb
To reduce load on Yann's server :)
=> Switch MNIST URL to a mirror

dev_swift/01a_fastai_layers.ipynb, dev_swift/04_callbacks.ipynb, dev_swift/FastaiNotebook_01a_fastai_layers/Sources/FastaiNotebook_01a_fastai_layers/01a_fastai_layers.swift, dev_swift/FastaiNotebook_02_fully_connected/Sources/FastaiNotebook_02_fully_connected/01a_fastai_layers.swift, dev_swift/FastaiNotebook_02a_why_sqrt5/Sources/FastaiNotebook_02a_why_sqrt5/01a_fastai_layers.swift, dev_swift/FastaiNotebook_03_minibatch_training/Sources/FastaiNotebook_03_minibatch_training/01a_fastai_layers.swift, dev_swift/FastaiNotebook_04_callbacks/Sources/FastaiNotebook_04_callbacks/01a_fastai_layers.swift, dev_swift/FastaiNotebook_04_callbacks/Sources/FastaiNotebook_04_callbacks/04_callbacks.swift, dev_swift/FastaiNotebook_05_anneal/Sources/FastaiNotebook_05_anneal/01a_fastai_layers.swift, dev_swift/FastaiNotebook_05_anneal/Sources/FastaiNotebook_05_anneal/04_callbacks.swift, dev_swift/FastaiNotebook_05b_early_stopping/Sources/FastaiNotebook_05b_early_stopping/01a_fastai_layers.swift, dev_swift/FastaiNotebook_05b_early_stopping/Sources/FastaiNotebook_05b_early_stopping/04_callbacks.swift, dev_swift/FastaiNotebook_06_cuda/Sources/FastaiNotebook_06_cuda/01a_fastai_layers.swift, dev_swift/FastaiNotebook_06_cuda/Sources/FastaiNotebook_06_cuda/04_callbacks.swift, dev_swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/01a_fastai_layers.swift, dev_swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/04_callbacks.swift, dev_swift/FastaiNotebook_08_data_block/Sources/FastaiNotebook_08_data_block/01a_fastai_layers.swift, dev_swift/FastaiNotebook_08_data_block/Sources/FastaiNotebook_08_data_block/04_callbacks.swift, dev_swift/FastaiNotebook_08a_heterogeneous_dictionary/Sources/FastaiNotebook_08a_heterogeneous_dictionary/01a_fastai_layers.swift, dev_swift/FastaiNotebook_08a_heterogeneous_dictionary/Sources/FastaiNotebook_08a_heterogeneous_dictionary/04_callbacks.swift, dev_swift/FastaiNotebook_09_optimizer/Sources/FastaiNotebook_09_optimizer/01a_fastai_layers.swift, dev_swift/FastaiNotebook_09_optimizer/Sources/FastaiNotebook_09_optimizer/04_callbacks.swift, dev_swift/FastaiNotebooks/Sources/FastaiNotebooks/01a_fastai_layers.swift, dev_swift/FastaiNotebooks/Sources/FastaiNotebooks/04_callbacks.swift
This will make things incompatible with the previous nightly, so only merge if you're ready to switch over.
Subsequent notebooks will need similar updates.
Optimizer initialization is doing a non-ideal hack now.
=> make 04 work with latest nightly

dev_course/dl2/08_data_block.ipynb, dev_course/dl2/11_train_imagenette.ipynb
Using the exported method **model_summary(...)** outside of the notebook caused an error because the function uses a global scoped **'data'** variable.
**New signature**
```python
def model_summary(run, learn, data, find_all=False):
..
```
**New usage**
```python
model_summary(run, learn, data)
```
=> Added 'data' param on model_summary - it was inherited from global scope

dev_course/dl2/all_notebook2script.sh, dev_course/dl2/notebook2script.py
Simple build script to export all the notebooks in a row and update *.py files in "exp" folder.
=> Build script to export all notebooks

dev_course/dl2/12a_awd_lstm.ipynb
minor change to description: dimensions were mixed up in explanation.
=> Correct description of masking in 12a_awd_lstm.ipynb

dev_course/dl2/12_text.ipynb
- fix the argument name in TokenizerProcessor.proc1
- Add the superclass "Dataset" for LM_PreLoader for consistency
=> Fix typos in 12_text

dev_course/dl2/02_fully_connected.ipynb, dev_course/dl2/04_callbacks.ipynb, dev_course/dl2/notebook2script.py
Hi,
I've included the small changes mentioned in [#129](https://github.com/fastai/fastai_docs/issues/129#issue-444338559) and re-included 04_callbacks.ipnby which was deleted May 07 20:30 (5b1ee1cd08ff0805d03b9e437e8ee99d7bd05b52).
=> Fix typo + win compatibility + include missing notebook

environment.yml
Initial attempt at an environments.yml file for fastai_v2.  Let me know if you would like these to be in alphabetical order.  Trying to keep this as clean as possible to avoid unnecessary bloat.
=> Adding environment.yml

README.md
Added scipy dependency in conda command in README
=> Added scipy dependency

environment.yml
just realized nb 30 requires a spacy import so adding that to requirements.yml
=> add spacy for 30_text_core nb

dev/05_data_core.ipynb, dev/local/notebook/index.txt
Adding a new test for multicategory decode that didn't exist before.
=> add new test to MultiCategorize

environment.yml
=> + scikit-learn

dev/05_data_core.ipynb, dev/local/data/core.py
For the functions:
* get_files
* FileGetter
* get_image_files
* ImageGetter
=> Parameter renamed: include->folders

dev/21_tutorial_imagenette.ipynb
Signed-off-by: Insop Song <insop.song@gmail.com>
=> Fix minor typo

dev/03_data_pipeline.ipynb
Add new tests for `mk_transform`
These tests check that `mk_transform` converts a user-defined, pre-built, and lambda function to type `Transform`
=> Add new tests for mk_transform

dev/60_medical_imaging.ipynb, dev/local/medical/imaging.py
Add one liner docs to freqhist_bins based on Jeremy's kaggle kernel
https://www.kaggle.com/jhoward/don-t-see-like-a-radiologist-fastai
=> Add docs to frehist_bins fns

swift/07_batchnorm.ipynb, swift/FastaiNotebook_07_batchnorm/Sources/FastaiNotebook_07_batchnorm/07_batchnorm.swift, swift/FastaiNotebook_08_data_block/Sources/FastaiNotebook_08_data_block/07_batchnorm.swift, swift/FastaiNotebook_08a_heterogeneous_dictionary/Sources/FastaiNotebook_08a_heterogeneous_dictionary/07_batchnorm.swift, swift/FastaiNotebook_08c_data_block_generic/Sources/FastaiNotebook_08c_data_block_generic/07_batchnorm.swift, swift/FastaiNotebook_09_optimizer/Sources/FastaiNotebook_09_optimizer/07_batchnorm.swift, swift/FastaiNotebook_10_mixup_ls/Sources/FastaiNotebook_10_mixup_ls/07_batchnorm.swift, swift/FastaiNotebook_11_imagenette/Sources/FastaiNotebook_11_imagenette/07_batchnorm.swift
Works around https://bugs.swift.org/browse/TF-944 to unblock a merge from master.
=> TF-944 workaround

README.md
=> add scikit-image dep
