fastai/fastai_dev

docs_src/training.ipynb

We need to rename the output of `get_mnist()` to avoid clashes with fastai.data (imported with a *).

Rename MNIST data object to avoid name clash.

---

docs_src/callbacks.hooks.ipynb

Fix the order of axis in ActivationStats.stats.shape  from (2,num_batches,num_modules) to (2,num_modules,num_batches).
Link in forum: [stats shape](https://forums.fast.ai/t/developer-chat/22363/320)

fix shape in ActivationStats

---

dev_course/dl2/notebook2script.py

The `notebook2script.py` script should print output folder name. I didn't know the output file is in the `exp` folder until I read the source code.
Command:
```sh
!python notebook2script.py 00_exports.ipynb
```
Before:
Converted 00_exports.ipynb to nb_00.py
After:
Converted 00_exports.ipynb to exp/nb_00.py

print containing folder in output path

---

dev_swift/02a_why_sqrt5.ipynb

Currently meant to work as a standalone Colab, but I can also integrate it with the notebook-as-package infrastructure. Also includes a 10-line MNIST loader in plain Swift, which should likely replace `MnistDataset()`. More coming tomorrow.
Printing the values of individual weight gradients is blocked by TF-417.

Add Swift translation of conv init notebook

---

dev_course/dl2/03_minibatch_training.ipynb

In 'Pytorch DataLoader' session, new DataLoader class and objects are defined but loss and accuracy are calculated based on train batch from previous DataLoader, which is xb (e.g loss_func(model(xb), yb), accuracy(model(xb), yb)). I figure this won't affect the outputs at all since these data loaders are the same, but still...

update train_dl xb,yb for Pytorch DataLoader session

---

dev_swift/05b_early_stopping.ipynb

Add `train` function, which trains a given model on a given dataset, using
a given optimizer and loss function.
Todos:
- Integrate callbacks into `train`.
- `train` will be the analog of `class Runner`.
- Finish porting the Python `05b_early_stopping.ipynb` notebook.

[Swift] Add training loop abstraction.

---

dev_course/dl2/07_batchnorm.ipynb

When running the simplified RunningBatchNorm, I was getting the following error:
```
<ipython-input-16-6c81ad8a7715> in update_stats(self, x)
27         means = self.sums/self.count
28         varns = (self.sqrs/self.count).sub_(means*means)
---> 29         if bool(self.batch < 20): vars.clamp_min_(0.01)
30         self.factor = self.mults / (varns+self.eps).sqrt()
31         self.offset = self.adds - means*self.factor
AttributeError: 'builtin_function_or_method' object has no attribute 'clamp_min_'
```
I believe it is supposed to be `varns` instead.

Fixing a typo for `vars` vs. `varns`

---

dev_swift/04_callbacks.ipynb
dev_swift/05_anneal.ipynb

In the `DataBunch` definition, this replaces a call to `random()`  (which works on Linux but not on macOS), with the cross-platform expression `Int64.random(in:Int64.min..<Int64.max)`.
This also removes an Glibc import which had no effect on Linux and broke macOS.
This PR only updates the notebooks, and not the pre-generated Swift packages. (Should I update those too?)
I tested by running the 04 and the 05 notebooks. 04 works fine. 05 fails in the same way before and after the change, at cell 46, due to what I believe are unrelated issues with unresolved or identifiers.

Fix cross-platform random Int64 generation

---

dev_course/dl2/12c_ulmfit.ipynb

Store **index of word 'house' into a variable** to ensure that the test check works even after retraining model of previous notebook.
```python
idx_house_new, idx_house_old = vocab.index('house'),old_vocab.index('house')
...
house_wgt  = old_wgts['0.encoder.weight'][idx_house_old]
house_bias = old_wgts['1.decoder.bias'][idx_house_old] 
...
test_near(wgts['0.encoder.weight'][idx_house_new],house_wgt)
test_near(wgts['1.decoder.bias'][idx_house_new],house_bias)
```

Store 'house' dictionary index into a variable to fix test check

---

dev_swift/08_data_block.ipynb
dev_swift/FastaiNotebook_08_data_block/Sources/FastaiNotebook_08_data_block/08_data_block.swift
dev_swift/FastaiNotebook_08a_heterogeneous_dictionary/Sources/FastaiNotebook_08a_heterogeneous_dictionary/08_data_block.swift
dev_swift/FastaiNotebook_09_optimizer/Sources/FastaiNotebook_09_optimizer/08_data_block.swift
dev_swift/FastaiNotebook_10_mixup_ls/Sources/FastaiNotebook_10_mixup_ls/08_data_block.swift
dev_swift/FastaiNotebooks/Sources/FastaiNotebooks/08_data_block.swift

This PR fixes a bug in notebook 08 in `fetchFiles`, and updates all Swift files generated from that notebook.
It replaces a reference to a non-existent `.lowercased` property of `String` with the function call `lowercased()`. You can see there is such a function and no such property in the API docs: https://developer.apple.com/documentation/swift/string/1641392-lowercased.
So the real question is, why did this work at all? I don't know. I think it's a S4TF bug, or a consequence of the execution context of the jupyter environment.
I have tested and verified that all notebooks still run correctly on Ubuntu nightly 2019-04-21, and that the pre-generated Fastai Swift code still builds.
I found this bug while working on getting fastai running on macOS, where this produces a compilation error. …

Fix access to lowercased as var rather than function call

---

dev_swift/Runnable11/Sources/Runnable11/08_data_block.swift

This is a boring fix.
String.lowercased() is a function call not a computed property.
Treating it as a property works in Jupyter, but it should not.
We've fixed this everywhere else. The generated Swift in Runnable
must be out of date with what's exported from the notebooks.
This problem only affects the ability to compile on macOS.

Fix access to String.lowercased as var not func

---

dev_course/dl2/04_callbacks.ipynb

Fixed references to `learn` referred to the learner object created outside the class definition. Now they refer to the internal `self.learn` instead.

add self to learn references in callback definition

---

dev_swift/02_fully_connected.ipynb

Confirmed no other usages of `unbroadcast`:
```console
$ grep -nr "unbroadcast" dev_swift/**/*.swift dev_swift/**/*.ipynb
dev_swift/02_fully_connected.ipynb:1179:    "               𝛁out.unbroadcasted(to: b.shape))\n",
```
Up next: investigating gradient computation assertion failures. ([TF-596](https://bugs.swift.org/browse/TF-596))

[Swift] Rename `unbroadcast` to `unbroadcasted`.

---

dev_swift/02_fully_connected.ipynb

`reluGrad` should replace with zero for negative input scalars instead
of positive input scalars.
---
Verified this fixes `dev_swift/02_fully_connected.ipynb`.
I wasn't sure whether to strip or keep cell outputs, so I used my best judgement to update selected outputs. @sgugger: could you please clarify what to do with cell outputs?

[Swift] Fix relu gradient definition.

---

dev/92_notebook_showdoc.ipynb

TypeDispatch functions are unwrapped so `get_function_source` works
for`encodes` and `decodes` Transform methods.
`get_function_source` relies on `inspect.getsourcelines()`, which
expects some sort of callable object. However, `encodes` and `decodes`
are of type TypeDispatch, and `get_function_source` returns an empty
string. This, in turn, causes `show_doc` to generate an empty link.
When the notebook is exported to local/notebook/showdoc, it fixes the
source links for `Cuda.encodes` that were demonstrated during today's
code walk-thru in notebook `05_data_core`. The same thing would happen
for other transform encoding/decoding implementations such as those of
`OneHotEncode`.
~~Note that the source link for these methods points to a github revision,
whereas the links for other objects …

Attempt to fix source links for TypeDispatch properties

---

dev/05_data_core.ipynb

Currently we get an assertion error if we run Cuda Tfm tests on CPU only machine. 
`AssertionError: ==:
torch.LongTensor
torch.cuda.LongTensor`.
This pull request fixes that.

Update cuda tfm test to fix for cpu only machines

---

dev/05_data_core.ipynb

For normalization pipeline which includes `CUDA()`, if machine does not have GPU then `test_eq(x.type(), 'torch.cuda.FloatTensor')` test fails.
This PR fixes that.

Fix test for CPU only machine

---

dev/05_data_core.ipynb
dev/local/data/core.py

This is not a super big deal (I was even contemplating whether raising this makes sense), nonetheless submitting a PR :slightly_smiling_face:
`Categorize` works as expected with `add_na=True`, but with `add_na` we get the following behavior:
I am assuming this can potentially lead to subtle bugs.
Anyhow, really not sure if the proposed change is a step in the right direction :slightly_smiling_face: Happy to make any changes to the PR that might be needed or to close it altogether!

Categorize to raise error on unseen label with add_na=False

---

dev/91_notebook_export.ipynb
dev/92_notebook_showdoc.ipynb
dev/local/notebook/export.py
dev/local/notebook/showdoc.py

Both `source_nb` and `show_doc` should work correctly now. Use, for example, `DataBunch.train_dl` to test - I added a couple of tests in the notebook, but commented out to avoid circular references.
Note, however, that the qualified name returned by `get_name` is an approximation (it points to the name of the property getter, if it exists; or the name of the object that owns the property). I couldn't find a way to obtain the actual name of the property. However, this approach suffices to make the relevant cross-reference functions work: `source_nb`, `get_source_link`, `show_doc`.
Addresses #187.

Allow cross-reference links to work for properties

---

dev/06_data_source.ipynb

- 06_data_source.ipynb
Fix test
```
inp = pd.DataFrame(dict(a=[5,1,2,3,4]))
dsrc = DataSource(inp, tfms=itemgetter(0)).subset(0)
test_eq(*dsrc[2], (2,))          # Retrieve one item (subset 0 is the default)
test_eq(dsrc[1,2], [(1,),(2,)])    # Retrieve two items by index
mask = [True,False,False,True,False]
test_eq(dsrc[mask], [(5,),(3,)])   # Retrieve two items by mask
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-1fbb307a45fd> in <module>
1 inp = pd.DataFrame(dict(a=[5,1,2,3,4]))
2 dsrc = DataSource(inp, tfms=itemgetter(0)).subset(0)
----> 3 test_eq(*dsrc[2], (2,))          # Retrieve one item (subset 0 is the default)
4 test_eq(dsrc[1,2], [(1,),(2,)]) …
```

Fix test for Datasource, Retrieve one item

---

dev/local/callback/progress.py

CSVLogger was missing the run_after indicator, which can cause an error.

CSVLogger: add missing run_after indicator

---

dev/08_vision_core.ipynb

Looks like this is an extra cell inside vision.core. 
Adding this PR to remove this cell from the notebook which also shows in docs here:
http://dev.fast.ai/vision.core.html#Image.reshape

Remove extra cell (perhaps added by mistake)

---

dev/01b_core_dispatch.ipynb
dev/local/core/dispatch.py

While looking into `DataSource` I got an error 
```
AttributeError: 'RegexLabeller' object has no attribute '__name__'
```
This can be replicated by:
```
path = untar_data(URLs.PETS); path
np.random.seed(2)
pat = r'/([^/]+)_\d+.jpg$'
items = get_image_files(path/'images')
tfms = L([PILBase.create], [RegexLabeller(pat), Categorize])
splits = RandomSplitter(0.2)(items)
dsrc = DataSource(items, tfms=tfms, splits=splits)
dsrc.tls
```
From what I understand, issue occurs due to calling `__name__` on RegexLabeller() and this PR attempts to fix it.

fix RegexLabeller obj has no attr __name__
